import './globals.css'
import Nav from '@/components/Navigation'
import { Providers } from './provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Nav />

          {children}
        </Providers>
      </body>
    </html>
  )
}
